### PR TITLE
Fixes #3270: Read Result better and use POD UID to double check before …

### LINKED ISSUE #3270: When deleting sgp pod with --force option, the ip rules are not deleted intermettently.
**What happened**:
When deleting sgp pods with --force option, the ip rules are not deleted intermettently. 
Moreover it leads to networking issue making a pod isolated and having no connections. This situation is escalated when the statefulset with sgp restarted by rolling out. 

**Attach logs**
```
{"level":"info","ts":"2025-04-23T11:23:13.295Z","caller":"routed-eni-cni-plugin/cni.go:128","msg":"Received CNI add request: ContainerID(923f4047456d842459336f3993ec5162dc8ba8804b63b648daf0e1ee895ccbe5) Netns(/var/run/netns/cni-a6f50f45-a6c1-e247-ab62-555960203f16) IfName(eth0) Args(K8S_POD_NAME=jjobs-agent-cfw-1;K8S_POD_INFRA_CONTAINER_ID=923f4047456d842459336f3993ec5162dc8ba8804b63b648daf0e1ee895ccbe5;K8S_POD_UID=d3452531-b2e7-4238-ac50-b02e1876d3fa;IgnoreUnknown=1;K8S_POD_NAMESPACE=card) Path(/opt/cni/bin) argsStdinData({\"cniVersion\":\"0.4.0\",\"mtu\":\"9001\",\"name\":\"aws-cni\",\"pluginLogFile\":\"/var/log/aws-routed-eni/plugin.log\",\"pluginLogLevel\":\"DEBUG\",\"podSGEnforcingMode\":\"standard\",\"type\":\"aws-cni\",\"vethPrefix\":\"eni\"})"}
{"level":"info","ts":"2025-04-23T11:23:13.333Z","caller":"routed-eni-cni-plugin/cni.go:314","msg":"Received CNI del request: ContainerID(923f4047456d842459336f3993ec5162dc8ba8804b63b648daf0e1ee895ccbe5) Netns(/var/run/netns/cni-a6f50f45-a6c1-e247-ab62-555960203f16) IfName(eth0) Args(IgnoreUnknown=1;K8S_POD_NAMESPACE=card;K8S_POD_NAME=jjobs-agent-cfw-1;K8S_POD_INFRA_CONTAINER_ID=923f4047456d842459336f3993ec5162dc8ba8804b63b648daf0e1ee895ccbe5;K8S_POD_UID=d3452531-b2e7-4238-ac50-b02e1876d3fa) Path(/opt/cni/bin) argsStdinData({\"cniVersion\":\"0.4.0\",\"mtu\":\"9001\",\"name\":\"aws-cni\",\"pluginLogFile\":\"/var/log/aws-routed-eni/plugin.log\",\"pluginLogLevel\":\"DEBUG\",\"podSGEnforcingMode\":\"standard\",\"type\":\"aws-cni\",\"vethPrefix\":\"eni\"})"}
{"level":"info","ts":"2025-04-23T11:23:13.689Z","caller":"routed-eni-cni-plugin/cni.go:128","msg":"Received CNI add request: ContainerID(4c433f1ca52f33c7e761737fa17c1dffc4622658f5b7c3b51cddfe446a8db692) Netns(/var/run/netns/cni-9fbe32fd-66cd-4227-5717-7386680cc08a) IfName(eth0) Args(K8S_POD_NAME=jjobs-agent-cfw-1;K8S_POD_INFRA_CONTAINER_ID=4c433f1ca52f33c7e761737fa17c1dffc4622658f5b7c3b51cddfe446a8db692;K8S_POD_UID=d3452531-b2e7-4238-ac50-b02e1876d3fa;IgnoreUnknown=1;K8S_POD_NAMESPACE=card) Path(/opt/cni/bin) argsStdinData({\"cniVersion\":\"0.4.0\",\"mtu\":\"9001\",\"name\":\"aws-cni\",\"pluginLogFile\":\"/var/log/aws-routed-eni/plugin.log\",\"pluginLogLevel\":\"DEBUG\",\"podSGEnforcingMode\":\"standard\",\"type\":\"aws-cni\",\"vethPrefix\":\"eni\"})"}
{"level":"info","ts":"2025-04-23T11:23:43.760Z","caller":"routed-eni-cni-plugin/cni.go:314","msg":"Received CNI del request: ContainerID(1f14fcd055345aa25e2076d440757fe33ac827d970753f184bae772cd0712cf6) Netns(/var/run/netns/cni-65ffbc0a-2d24-3e56-7258-5f6cc33b09c2) IfName(eth0) Args(K8S_POD_INFRA_CONTAINER_ID=1f14fcd055345aa25e2076d440757fe33ac827d970753f184bae772cd0712cf6;K8S_POD_UID=6e28c408-b2b5-4934-8261-8adae0ec79d3;IgnoreUnknown=1;K8S_POD_NAMESPACE=card;K8S_POD_NAME=jjobs-agent-cfw-1) Path(/opt/cni/bin) argsStdinData({\"cniVersion\":\"0.4.0\",\"mtu\":\"9001\",\"name\":\"aws-cni\",\"pluginLogFile\":\"/var/log/aws-routed-eni/plugin.log\",\"pluginLogLevel\":\"DEBUG\",\"podSGEnforcingMode\":\"standard\",\"prevResult\":{\"cniVersion\":\"0.4.0\",\"interfaces\":[{\"name\":\"eni9b44bf08241\"},{\"name\":\"eth0\",\"sandbox\":\"/var/run/netns/cni-65ffbc0a-2d24-3e56-7258-5f6cc33b09c2\"},{\"name\":\"dummy9b44bf08241\",\"mac\":\"3\"}],\"ips\":[{\"version\":\"4\",\"interface\":1,\"address\":\"10.234.18.235/32\",\"gateway\":\"10.234.16.1\"}],\"dns\":{}},\"type\":\"aws-cni\",\"vethPrefix\":\"eni\"})"}
{"level":"info","ts":"2025-04-23T11:23:43.761Z","caller":"routed-eni-cni-plugin/cni.go:314","msg":"Received del network response from ipamd for pod jjobs-agent-cfw-1 namespace card sandbox 1f14fcd055345aa25e2076d440757fe33ac827d970753f184bae772cd0712cf6: Success:true  IPv4Addr:\"10.234.18.73\"  PodVlanId:5"}
{"level":"info","ts":"2025-04-23T11:23:54.940Z","caller":"routed-eni-cni-plugin/cni.go:314","msg":"Received CNI del request: ContainerID(1f14fcd055345aa25e2076d440757fe33ac827d970753f184bae772cd0712cf6) Netns() IfName(eth0) Args(K8S_POD_UID=6e28c408-b2b5-4934-8261-8adae0ec79d3;IgnoreUnknown=1;K8S_POD_NAMESPACE=card;K8S_POD_NAME=jjobs-agent-cfw-1;K8S_POD_INFRA_CONTAINER_ID=1f14fcd055345aa25e2076d440757fe33ac827d970753f184bae772cd0712cf6) Path(/opt/cni/bin) argsStdinData({\"cniVersion\":\"0.4.0\",\"mtu\":\"9001\",\"name\":\"aws-cni\",\"pluginLogFile\":\"/var/log/aws-routed-eni/plugin.log\",\"pluginLogLevel\":\"DEBUG\",\"podSGEnforcingMode\":\"standard\",\"type\":\"aws-cni\",\"vethPrefix\":\"eni\"})"}
{"level":"info","ts":"2025-04-23T11:23:54.941Z","caller":"routed-eni-cni-plugin/cni.go:314","msg":"Received del network response from ipamd for pod jjobs-agent-cfw-1 namespace card sandbox 1f14fcd055345aa25e2076d440757fe33ac827d970753f184bae772cd0712cf6: Success:true  IPv4Addr:\"10.234.18.73\"  PodVlanId:5"}
{"level":"info","ts":"2025-04-23T11:23:54.941Z","caller":"routed-eni-cni-plugin/cni.go:314","msg":"Ignoring TeardownPodENI as Netns is empty for SG pod:jjobs-agent-cfw-1 namespace: card containerID:1f14fcd055345aa25e2076d440757fe33ac827d970753f184bae772cd0712cf6"}
{"level":"info","ts":"2025-04-23T11:23:54.958Z","caller":"routed-eni-cni-plugin/cni.go:314","msg":"Received CNI del request: ContainerID(1f14fcd055345aa25e2076d440757fe33ac827d970753f184bae772cd0712cf6) Netns() IfName(eth0) Args(K8S_POD_INFRA_CONTAINER_ID=1f14fcd055345aa25e2076d440757fe33ac827d970753f184bae772cd0712cf6;K8S_POD_UID=6e28c408-b2b5-4934-8261-8adae0ec79d3;IgnoreUnknown=1;K8S_POD_NAMESPACE=card;K8S_POD_NAME=jjobs-agent-cfw-1) Path(/opt/cni/bin) argsStdinData({\"cniVersion\":\"0.4.0\",\"mtu\":\"9001\",\"name\":\"aws-cni\",\"pluginLogFile\":\"/var/log/aws-routed-eni/plugin.log\",\"pluginLogLevel\":\"DEBUG\",\"podSGEnforcingMode\":\"standard\",\"type\":\"aws-cni\",\"vethPrefix\":\"eni\"})"}
{"level":"info","ts":"2025-04-23T11:23:54.959Z","caller":"routed-eni-cni-plugin/cni.go:314","msg":"Received del network response from ipamd for pod jjobs-agent-cfw-1 namespace card sandbox 1f14fcd055345aa25e2076d440757fe33ac827d970753f184bae772cd0712cf6: Success:true  IPv4Addr:\"10.234.18.73\"  PodVlanId:5"}
{"level":"info","ts":"2025-04-23T11:23:54.959Z","caller":"routed-eni-cni-plugin/cni.go:314","msg":"Ignoring TeardownPodENI as Netns is empty for SG pod:jjobs-agent-cfw-1 namespace: card containerID:1f14fcd055345aa25e2076d440757fe33ac827d970753f184bae772cd0712cf6"}
```

**What you expected to happen**:
When a pod is assigned an IP and the IP is about to add to routing and rule, if a routing rule for that IP already exists that is garbage, the ip should be cleaned up and it could be alleviate this issue. 

**How to reproduce it (as minimally and precisely as possible)**:
I have used the below template spec, and the commands by exeucting multiple times:
```
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - image: openjdk:17-alpine
    imagePullPolicy: Always
    command: ["sleep", "3600"]
    name: java
    resources:
      limits:
        vpc.amazonaws.com/pod-eni: "1"
      requests:
        vpc.amazonaws.com/pod-eni: "1"
    volumeMounts:
    - name: script-volume
      mountPath: /scripts
  terminationGracePeriodSeconds: 5
  nodeName: node-xxxxx
  volumes:
  - name: script-volume
    configMap:
      name: script-config
      defaultMode: 0755
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: script-config
data:
  lookup.sh: |
    #!/bin/bash
    cat <<EOF > HostnameResolver.java
    import java.net.InetAddress;
    import java.net.UnknownHostException;
    public class HostnameResolver {
      public static void main(String[] args) {
        String hostname = "xxxxx.sk1.region.eks.amazonaws.com";
        if(args.length > 0) {
          hostname = args[0];
        }
        try {
          System.out.println("Hostname: " + hostname);
          InetAddress[] addresses = InetAddress.getAllByName(hostname);
          for (InetAddress addr : addresses) {
            System.out.println("IP Address: " + addr.getHostAddress());
          }
        } catch (UnknownHostException e) {
          System.err.println("Could not find the host: " + hostname);
          e.printStackTrace();
          System.exit(1);
        }
        System.exit(0);
      }
    }
    EOF
    javac HostnameResolver.java
    echo "pod IP: $(hostname -i)"
    java HostnameResolver && exit
---
apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: test
spec:
  podSelector: {}
  securityGroups:
    groupIds:
      - sg-xxxxxx
```
The commands that we executed are as below:
```
#!/bin/bash
while true
do
    kubectl apply -f pod.yaml
    kubectl wait --for=condition=Ready pod/test
    kubectl exec -it test -- /bin/sh/scripts/lookup.sh
    kubectl delete -f pod.yaml --force
done
```

**Anything else we need to know?**:
For more information, please reach out to the Support case, 174289109400519.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.32
- CNI Version : v1.19.2
- OS (e.g: `cat /etc/os-release`): 
- Kernel (e.g. `uname -a`): Linux  5.10.233-224.894.amzn2.x86_64 #1 SMP  x86_64 x86_64 x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by Supreeth095**
**What type of PR is this?**
bug

**Which issue does this PR fix?**
#3270

**What does this PR do / Why do we need it?**:
1. Including K8S_POD_UID  - additional check before pod cleanup
2.  In tryDelWithPrevResult and teardownPodNetworkWithPrevResult , The changes prevent crashes or errors when PrevResult is missing or incompatible, ensuring the plugin works reliably across different CNI spec versions

**Will this PR introduce any new dependencies?**:
No new dependencies are introduced.

**Will this break upgrades or downgrades? Has updating a running cluster been tested?**:
Upgrades and downgrades should be safe.

**Does this change require updates to the CNI daemonset config files to work?**:
No CNI configuration or daemonset change

**Does this PR introduce any user-facing change?**:
No

Test Docs: https://github.com/aws/amazon-vpc-cni-k8s/pull/3304#issuecomment-2964629634

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: pkg/ipamd/rpc_handler.go [hunk 1]
```diff
@@ -294,6 +294,10 @@ func (s *server) DelNetwork(ctx context.Context, in *rpc.DelNetworkRequest) (*rp
 			return &rpc.DelNetworkReply{Success: false}, err
 		}
 		val, branch := pod.Annotations["vpc.amazonaws.com/pod-eni"]
+		if string(pod.ObjectMeta.UID) != in.K8S_POD_UID {
+			log.Errorf("Send DelNetworkReply: pod UID mismatch")
+			return &rpc.DelNetworkReply{Success: true}, nil
```
Comment (jaydeokar) [inline pkg/ipamd/rpc_handler.go]: Success should not be true here

File: rpc/rpc.pb.go [hunk 2]
```diff
@@ -273,6 +273,7 @@ type DelNetworkRequest struct {
 	K8S_POD_NAME               string `protobuf:"bytes,1,opt,name=K8S_POD_NAME,json=K8SPODNAME,proto3" json:"K8S_POD_NAME,omitempty"`
 	K8S_POD_NAMESPACE          string `protobuf:"bytes,2,opt,name=K8S_POD_NAMESPACE,json=K8SPODNAMESPACE,proto3" json:"K8S_POD_NAMESPACE,omitempty"`
 	K8S_POD_INFRA_CONTAINER_ID string `protobuf:"bytes,3,opt,name=K8S_POD_INFRA_CONTAINER_ID,json=K8SPODINFRACONTAINERID,proto3" json:"K8S_POD_INFRA_CONTAINER_ID,omitempty"`
+	K8S_POD_UID                string `protobuf:"bytes,4,opt,name=K8S_POD_UID,json=K8SPODUID,proto3" json:"K8S_POD_UID,omitempty"`
```
Comment (jaydeokar) [inline rpc/rpc.pb.go]: You need to regenerate the file instead of just updating the variable

Comment (jaydeokar) [reply rpc/rpc.pb.go]: The change should be in rpc.proto and then regenerate this file

File: pkg/ipamd/rpc_handler.go (hunk 1 above)
Comment (Supreeth095) [reply pkg/ipamd/rpc_handler.go]: Changed Success to be false and return and error.

File: rpc/rpc.pb.go (hunk 2 above)
Comment (Supreeth095) [reply rpc/rpc.pb.go]: Moved change to rpc.proto and regenerated the file.

**Comment by jaydeokar** [comment]
Please add unit tests and integration tests to this so that we can catch if delwithPrevResult is working as expected

File: cmd/routed-eni-cni-plugin/cni_test.go [hunk 3]
```diff
@@ -570,6 +571,7 @@ func Test_tryDelWithPrevResult(t *testing.T) {
 				conf: &NetConf{
 					NetConf: types.NetConf{
 						PrevResult: &current.Result{
+							CNIVersion: "1.0.0",
```
Comment (jaydeokar) [inline cmd/routed-eni-cni-plugin/cni_test.go]: This has to be "0.4.0"

https://github.com/aws/amazon-vpc-cni-k8s/blob/master/misc/10-aws.conflist#L2

Comment (Supreeth095) [reply cmd/routed-eni-cni-plugin/cni_test.go]: changed it to 0.4.0. But I must change current to point to 040 as well only in the test, as current used to typecast now./

File: cmd/routed-eni-cni-plugin/cni.go [hunk 4]
```diff
@@ -533,18 +539,25 @@ func tryDelWithPrevResult(driverClient driver.NetworkAPIs, conf *NetConf, k8sArg
...
-	if !ok {
-		log.Infof("PrevResult not available for pod. Pod may have already been deleted.")
+
+	if conf.PrevResult == nil {
 		return false
 	}
+	
+	prevResult, err := current.NewResultFromResult(conf.PrevResult)
+	if err != nil {
+		log.Infof("Ignoring teardownPodNetworkWithPrevResult as PrevResult is available for pod or parsing failed")
```
Comment (jaydeokar) [inline cmd/routed-eni-cni-plugin/cni.go]: Ignoring teardownPodNetworkWithPrevResult as PrevResult is **not** available for

**Comment by Supreeth095** [comment]
Integration Test Results:
[Integration_Test.txt](https://github.com/user-attachments/files/20699578/Integration_Test.txt)

Unit Test Results:
[UT.txt](https://github.com/user-attachments/files/20699626/UT.txt)

Manual Testing:
[ManualTesting.txt](https://github.com/user-attachments/files/20699764/ManualTesting.txt)

File: cmd/routed-eni-cni-plugin/cni.go (hunk 4 above)
Comment (Supreeth095) [reply cmd/routed-eni-cni-plugin/cni.go]: Fixed the log.

File: cmd/routed-eni-cni-plugin/cni.go [hunk 5]
```diff
@@ -533,18 +539,25 @@ func tryDelWithPrevResult(driverClient driver.NetworkAPIs, conf *NetConf, k8sArg
...
-		log.Infof("PrevResult not available for pod. Pod may have already been deleted.")
+
+	if conf.PrevResult == nil {
 		return false
 	}
+	
+	prevResult, err := current.NewResultFromResult(conf.PrevResult)
+	if err != nil {
+		log.Infof("Ignoring teardownPodNetworkWithPrevResult as PrevResult is not available for pod or parsing failed")
+		return false
```
Comment (haouc) [inline cmd/routed-eni-cni-plugin/cni.go:558]: What could be consequences if we return false?

File: pkg/ipamd/rpc_handler.go [hunk 6]
```diff
@@ -293,6 +294,11 @@ func (s *server) DelNetwork(ctx context.Context, in *rpc.DelNetworkRequest) (*rp
 			log.Warnf("Send DelNetworkReply: Failed to get pod spec: %v", err)
 			return &rpc.DelNetworkReply{Success: false}, err
 		}
+		if string(pod.ObjectMeta.UID) != in.K8S_POD_UID {
+			log.Errorf("Send DelNetworkReply: pod UID mismatch")
```
Comment (haouc) [inline pkg/ipamd/rpc_handler.go:298]: Error message can be logged out when bubbling up to caller? This error log looks redundant.

Comment (haouc) [reply pkg/ipamd/rpc_handler.go:298]: Also I am not sure if we should return failure if pod's ID doesn't match. Would failure cause other cascading cleanup being messed up if the requested pod is just wrong?

File: cmd/routed-eni-cni-plugin/cni.go (hunk 5 above)
Comment (Supreeth095) [reply cmd/routed-eni-cni-plugin/cni.go:558]: No Consequence - Looks like this is designed as a fallback mechanism when IPAMD is unreachable, so a false return does nothing. Just Prints log..!

@jaydeokar - Let me know if I am missing something.

**Comment by jaydeokar** [comment]
https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/pkg/multus/multus.go#L622-L631
Something similar used in multus

File: pkg/ipamd/rpc_handler.go (hunk 6 above)
Comment (Supreeth095) [reply pkg/ipamd/rpc_handler.go:298]: Ok. Do we not return anything, and just add a log if POD UID doesn't match, then?
cc: @jaydeokar

Comment (jaydeokar) [reply pkg/ipamd/rpc_handler.go:298]: Yeah this will not change the behavior from previous i.e when IPAMD fails and prev result doesn't exist. The pods will exist on the node and it's assumed kubelet will retry the delete

File: cmd/routed-eni-cni-plugin/cni.go (hunk 5 above)
Comment (jaydeokar) [reply cmd/routed-eni-cni-plugin/cni.go:558]: This will be same as the current behavior i.e the case when IPAMD fails and Prev result parsing fails or prev result does not exist. 
The pods will continue to exist, and kubelet should retry the delete

File: pkg/ipamd/rpc_handler.go (hunk 6 above)
Comment (jaydeokar) [reply pkg/ipamd/rpc_handler.go:298]: Ideally they are always the same we did verify in testing. As this only affects SGP pod, we can run some scale tests to verify if anything else is breaking. 

We only reach here if the prev result parsing fails for SGP pod.

**Review by haouc — APPROVED** [review]
lgtm

File: pkg/ipamd/rpc_handler.go [hunk 7]
```diff
@@ -293,6 +294,11 @@ func (s *server) DelNetwork(ctx context.Context, in *rpc.DelNetworkRequest) (*rp
 			log.Warnf("Send DelNetworkReply: Failed to get pod spec: %v", err)
 			return &rpc.DelNetworkReply{Success: false}, err
 		}
+		if (in.K8S_POD_UID != "") && (string(pod.ObjectMeta.UID) != in.K8S_POD_UID) {
```
Comment (haouc) [inline pkg/ipamd/rpc_handler.go]: I think this changed since my last review? Is this right to check if it is `empty` as well?

Comment (haouc) [reply pkg/ipamd/rpc_handler.go]: Basically why do we need `in.K8S_POD_UID != ""` to take the precedence?

Comment (Supreeth095) [reply pkg/ipamd/rpc_handler.go]: https://github.com/aws/amazon-vpc-cni-k8s/pull/3304#issuecomment-2968298327
I see that in Multus they have this check..
I don't know if there is some corner case where K8S_POD_UID is not sent..?

Just added it to make sure K8S_POD_UID is valid.
I can get rid of this added check if you think it's not necessary.

Comment (haouc) [reply pkg/ipamd/rpc_handler.go]: I think pod's UID is guaranteed not empty and immutable. Since you are already checking `string(pod.ObjectMeta.UID) != in.K8S_POD_UID` which makes `in.K8S_POD_UID != ""` is redundant.
https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids

Comment (Supreeth095) [reply pkg/ipamd/rpc_handler.go]: Got it, Thanks. Updated the PR.

**Review by jaydeokar — APPROVED** [review]
lgtm
