### PR TITLE
IPAMD optimizations and makefile changes

### LINKED ISSUE #1834: Makefile Build improvement
**What would you like to be added**:

1. `make help`

displays

```
all                             Builds Init, CNI and metrics helper container images.
build-linux                     Build the VPC CNI plugin agent using the host's Go toolchain.
docker                          Build VPC CNI plugin & agent container image.
docker-init                     Build VPC CNI plugin Init container image.
docker-func-test                Run the built CNI container image to use in functional testing
unit-test                       Run unit tests
unit-test-race                  Run unit tests with race detection (can only be run natively)
build-docker-test               Build the unit test driver container image.
docker-unit-tests               Run unit tests inside of the testing container image.
build-metrics                   Build metrics helper agent.
docker-metrics                  Build metrics helper agent Docker image.
metrics-unit-test               Run metrics helper unit test suite (must be run natively).
docker-metrics-test             Run metrics helper unit test suite in a container.
generate-limits                 Generate limit file go code
plugins                         Fetch the CNI plugins
debug-script                    Fetching debug script from awslabs/amazon-eks-ami
check                           Run all source code checks.
lint                            Run golint on source code.
vet                             Run go vet on source code.
docker-vet                      Run go vet inside of a container.
format                          Format all Go source code files. (Note! integration_test.go has an upstream import dependency that doesn't match)
clean                           Clean temporary files and build artifacts from the project.
help                            Show this help.

```

This can be grouped together as given in the example here (https://www.thapaliya.com/en/writings/well-documented-makefiles/) and could help the user differentiate various targets easily.

**Why is this needed**:

Usability Improvement and Developer Productivity.

### LINKED ISSUE #1872: WARM IP/MINIMUM IP greater than Max IPs per ENI delays adding ENI to datastore
**What happened**:

If WARM_IP_TARGET or MINIMUM_IP_TARGET is greater than the max IPs per ENI then adding ENI and IPs to datastore will take more than 2 minutes or so. This would cause pods to be stuck in container creation.

**Attach logs**

Created ENI at ->
```
{"level":"info","ts":"2022-02-17T22:44:04.191Z","caller":"awsutils/awsutils.go:730","msg":"Created a new ENI: eni-0331a633ce7e6f0e6"}
```

```
{"level":"info","ts":"2022-02-17T22:44:06.001Z","caller":"ipamd/ipamd.go:861","msg":"Allocated 3 private IP addresses"}
```

Then we go into retry to find IPs in IMDS

Retry LOOP (12 max retries) ->

Initially ENI is not there in IMDS

```
{"level":"debug","ts":"2022-02-17T22:44:06.004Z","caller":"retry/retry.go:70","msg":"Not able to find the right ENI yet (attempt 1/12)"}
{"level":"debug","ts":"2022-02-17T22:44:06.111Z","caller":"retry/retry.go:70","msg":"Not able to find the right ENI yet (attempt 2/12)"}
```

Then secondary IP is not there in IMDS

```
{"level":"debug","ts":"2022-02-17T22:44:06.321Z","caller":"retry/retry.go:70","msg":"No secondary IPv4 addresses/prefixes available yet on ENI eni-0331a633ce7e6f0e6"}
{"level":"debug","ts":"2022-02-17T22:44:06.759Z","caller":"retry/retry.go:70","msg":"No secondary IPv4 addresses/prefixes available yet on ENI eni-0331a633ce7e6f0e6"}
{"level":"debug","ts":"2022-02-17T22:44:07.574Z","caller":"retry/retry.go:70","msg":"No secondary IPv4 addresses/prefixes available yet on ENI eni-0331a633ce7e6f0e6"}
```

Next we have secondary IPs but since Minimum IP target > max IPs per ENI, we are in retry loop -
```
{"level":"debug","ts":"2022-02-17T22:44:09.225Z","caller":"retry/retry.go:70","msg":"We have IPs allocated : 3 but wanted IPs : 5 and retry : 6"}
{"level":"debug","ts":"2022-02-17T22:44:12.908Z","caller":"retry/retry.go:70","msg":"We have IPs allocated : 3 but wanted IPs : 5 and retry : 7"}
{"level":"debug","ts":"2022-02-17T22:44:20.079Z","caller":"retry/retry.go:70","msg":"We have IPs allocated : 3 but wanted IPs : 5 and retry : 8"}
{"level":"debug","ts":"2022-02-17T22:44:33.576Z","caller":"retry/retry.go:70","msg":"We have IPs allocated : 3 but wanted IPs : 5 and retry : 9"}
{"level":"debug","ts":"2022-02-17T22:45:01.077Z","caller":"retry/retry.go:70","msg":"We have IPs allocated : 3 but wanted IPs : 5 and retry : 10"}
{"level":"debug","ts":"2022-02-17T22:45:53.959Z","caller":"retry/retry.go:70","msg":"We have IPs allocated : 3 but wanted IPs : 5 and retry : 11"}
{"level":"debug","ts":"2022-02-17T22:46:59.918Z","caller":"retry/retry.go:70","msg":"We have IPs allocated : 3 but wanted IPs : 5 and retry : 12"}
```

So basically we wasted 2 mins after IPs and ENI available in IMDS.

Until the last retry, ENI and IP wont be added to DB and pods will fail

Basically problem is here - https://github.com/aws/amazon-vpc-cni-k8s/blob/a17d14ee2bec8598a76dc126eb35ac45a4a6272f/pkg/awsutils/awsutils.go#L1512

This impacts warm IP and minimum IP greater than max IPs per ENI

**What you expected to happen**:
Once we have the max IP per ENI allocated, we need to skip from retry loop.

**How to reproduce it (as minimally and precisely as possible)**:
t3.small has max IPs per ENI = 3
Set MINIUM_IP_TARGET = 9

**Anything else we need to know?**:
N/A

**Environment**:
- Kubernetes version (use `kubectl version`): N/A
- CNI Version: Issue has been there even in older versions like 1.7.5 and beyond.
- OS (e.g: `cat /etc/os-release`): N/A
- Kernel (e.g. `uname -a`): N/A

### LINKED ISSUE #1967: CNI deletes in-use ENI after restart with stale IMDS, leaving pods without network connectivity
**What happened**:

A pod was found running with an IP not associated with the EC2 instance it was running on. Upon further investigation, we found that the CNI had allocated that IP to the pod, and then later deleted the ENI while it was in-use, killing network connectivity to the pod. Here's a walkthrough of the logs I think are relevant (will email full ones):

CNI startup, so far so good:
```json
{"level":"info","ts":"2022-04-12T18:09:00.272Z","caller":"aws-k8s-agent/main.go:27","msg":"Starting L-IPAMD   ..."}
{"level":"info","ts":"2022-04-12T18:09:00.273Z","caller":"aws-k8s-agent/main.go:42","msg":"Testing communication with server"}
{"level":"info","ts":"2022-04-12T18:09:00.311Z","caller":"aws-k8s-agent/main.go:42","msg":"Successful communication with the Cluster! Cluster Version is: v1.20. git version: v1.20.10. git tree state: clean. commit: 8152330a2b6ca3621196e62966ef761b8f5a61bb. platform: linux/amd64"}
```

Shortly thereafter, it creates its first ENI (`eni-08c...`), which is the one it will later free while in-use:
```json
{"level":"info","ts":"2022-04-12T18:09:06.467Z","caller":"awsutils/awsutils.go:730","msg":"Creating ENI with security groups: [sg-0179e0179f3e93bab] in subnet: subnet-07e1bb9d6ebd2e0de"}
{"level":"info","ts":"2022-04-12T18:09:06.882Z","caller":"awsutils/awsutils.go:730","msg":"Created a new ENI: eni-08c872dba81641a42"}
{"level":"info","ts":"2022-04-12T18:09:08.031Z","caller":"ipamd/ipamd.go:853","msg":"Successfully created and attached a new ENI eni-08c872dba81641a42 to instance"}
{"level":"info","ts":"2022-04-12T18:09:08.031Z","caller":"ipamd/ipamd.go:862","msg":"Trying to allocate 14 IP addresses on ENI eni-08c872dba81641a42"}
{"level":"info","ts":"2022-04-12T18:09:08.431Z","caller":"ipamd/ipamd.go:862","msg":"Allocated 14 private IP addresses"}
```

But it spent the next three minutes unable to actually hand out any of the IPs it just allocated:
```json
{"level":"info","ts":"2022-04-12T18:09:10.496Z","caller":"rpc/rpc.pb.go:713","msg":"Received AddNetwork for NS /var/run/netns/bfda097f-fa1f-4e12-a177-1a5f1c10af84, Sandbox 82dc579a09949d5872fdc41bfe4bbdfe0f2afb932ee68b1ccd27b43c31834287, ifname eth0"}
{"level":"error","ts":"2022-04-12T18:09:10.496Z","caller":"datastore/data_store.go:680","msg":"DataStore has no available IP/Prefix addresses"}
{"level":"info","ts":"2022-04-12T18:09:10.513Z","caller":"rpc/rpc.pb.go:713","msg":"Send AddNetworkReply: IPv4Addr , IPv6Addr: , DeviceNumber: -1, err: assignPodIPv4AddressUnsafe: no available IP/Prefix addresses"}
...
{"level":"error","ts":"2022-04-12T18:12:07.852Z","caller":"datastore/data_store.go:680","msg":"DataStore has no available IP/Prefix addresses"}
{"level":"info","ts":"2022-04-12T18:12:07.870Z","caller":"rpc/rpc.pb.go:713","msg":"Send AddNetworkReply: IPv4Addr , IPv6Addr: , DeviceNumber: -1, err: assignPodIPv4AddressUnsafe: no available IP/Prefix addresses"}
```

Apparently because the IMDS was stale:
```json
{"level":"error","ts":"2022-04-12T18:12:08.766Z","caller":"ipamd/ipamd.go:812","msg":"Failed to increase pool size: Unable to discover attached ENI from metadata service waitForENIAndIPsAttached: giving up trying to retrieve ENIs from metadata service"}
```

So it triggers a resync from the EC2 API. It also allocates 14 more IPs here:

```json
{"level":"info","ts":"2022-04-12T18:12:11.412Z","caller":"ipamd/ipamd.go:1318","msg":"Got network cardindex 0 for ENI eni-08c872dba81641a42"}
{"level":"info","ts":"2022-04-12T18:12:11.412Z","caller":"ipamd/ipamd.go:1318","msg":"eni-08c872dba81641a42 is of type: interface"}
{"level":"info","ts":"2022-04-12T18:12:11.412Z","caller":"awsutils/awsutils.go:1201","msg":"logOutOfSyncState: DescribeNetworkInterfaces(eni-08c872dba81641a42) yielded private IPv4 addresses 100.68.33.202,100.68.35.149,100.68.35.40,100.68.36.147,100.68.37.227,100.68.40.230,100.68.41.40,100.68.42.38,100.68.55.166,100.68.58.43,100.68.61.197,100.68.63.104,100.68.63.144,100.68.63.219 that were not yet found in IMDS."}
{"level":"info","ts":"2022-04-12T18:12:11.412Z","caller":"ipamd/ipamd.go:1318","msg":"Got network cardindex 0 for ENI eni-0c7c58f6368533bd1"}
{"level":"info","ts":"2022-04-12T18:12:11.412Z","caller":"ipamd/ipamd.go:1318","msg":"eni-0c7c58f6368533bd1 is of type: interface"}
{"level":"info","ts":"2022-04-12T18:12:11.412Z","caller":"networkutils/network.go:904","msg":"Setting up network for an ENI with IP address 100.68.41.92, MAC address 06:ad:59:59:f9:65, CIDR 100.68.32.0/19 and route table 2"}
{"level":"info","ts":"2022-04-12T18:12:11.421Z","caller":"ipamd/ipamd.go:1372","msg":"Found ENIs having 1 secondary IPs and 0 Prefixes"}
{"level":"info","ts":"2022-04-12T18:12:11.421Z","caller":"ipamd/ipamd.go:1422","msg":"Reconcile and skip primary IP 10.7.8.73 on ENI eni-0c7c58f6368533bd1"}
{"level":"info","ts":"2022-04-12T18:12:13.921Z","caller":"ipamd/ipamd.go:935","msg":"Trying to allocate 14 IP addresses on ENI eni-08c872dba81641a42"}
{"level":"info","ts":"2022-04-12T18:12:14.356Z","caller":"ipamd/ipamd.go:1077","msg":"Adding 100.68.61.197/32 to DS for eni-08c872dba81641a42"}
{"level":"info","ts":"2022-04-12T18:12:14.356Z","caller":"ipamd/ipamd.go:1077","msg":"Added ENI(eni-08c872dba81641a42)'s IP/Prefix 100.68.61.197/32 to datastore"}
...
{"level":"info","ts":"2022-04-12T18:12:14.356Z","caller":"ipamd/ipamd.go:1077","msg":"Adding 100.68.41.40/32 to DS for eni-08c872dba81641a42"}
{"level":"info","ts":"2022-04-12T18:12:14.356Z","caller":"ipamd/ipamd.go:1077","msg":"Added ENI(eni-08c872dba81641a42)'s IP/Prefix 100.68.41.40/32 to datastore"}
...
```

Having done that, it then handles four AddNetworkRequests successfully, including assigning 100.68.41.40 to the pod that brought this issue to our attention:

```json
{"level":"info","ts":"2022-04-12T18:12:16.851Z","caller":"rpc/rpc.pb.go:713","msg":"Received AddNetwork for NS /var/run/netns/76c30140-c4c8-4408-a445-9f73cb3489a2, Sandbox be11ae75f40d6dfc666fb96a568f94ebc264122000af5edb3752389e1d092e1a, ifname eth0"}
{"level":"info","ts":"2022-04-12T18:12:16.851Z","caller":"datastore/data_store.go:784","msg":"AssignPodIPv4Address: Assign IP 100.68.41.40 to sandbox aws-cni/be11ae75f40d6dfc666fb96a568f94ebc264122000af5edb3752389e1d092e1a/eth0"}
...
{"level":"info","ts":"2022-04-12T18:12:22.884Z","caller":"rpc/rpc.pb.go:713","msg":"Send AddNetworkReply: IPv4Addr 100.68.61.197, IPv6Addr: , DeviceNumber: 1, err: <nil>"}
```

Then it starts another resync -- not sure what triggers it. The pod is replaced shortly thereafter -- this lines up with a rolling update to adjust the resource requests.

```json
{"level":"info","ts":"2022-04-12T18:13:16.877Z","caller":"ipamd/ipamd.go:1422","msg":"Reconcile and skip primary IP 10.7.8.73 on ENI eni-0c7c58f6368533bd1"}
{"level":"warn","ts":"2022-04-12T18:13:16.878Z","caller":"ipamd/ipamd.go:1350","msg":"Instance metadata does not match data store! ipPool: [100.68.35.40 100.68.63.144 100.68.61.197 100.68.55.166 100.68.63.219 100.68.33.202 100.68.35.149 100.68.41.40 100.68.58.43 100.68.37.227 100.68.63.104 100.68.36.147 100.68.42.38 100.68.40.230], metadata: [{\n  Primary: true,\n  PrivateIpAddress: \"100.68.41.92\"\n}]"}
{"level":"info","ts":"2022-04-12T18:13:16.976Z","caller":"ipamd/ipamd.go:1422","msg":"Reconcile and skip primary IP 100.68.41.92 on ENI eni-08c872dba81641a42"}
{"level":"info","ts":"2022-04-12T18:13:16.976Z","caller":"ipamd/ipamd.go:1422","msg":"Trying to add 100.68.61.197"}
{"level":"info","ts":"2022-04-12T18:13:16.976Z","caller":"ipamd/ipamd.go:1546","msg":"Adding 100.68.61.197/32 to DS for eni-08c872dba81641a42"}
{"level":"info","ts":"2022-04-12T18:13:16.976Z","caller":"ipamd/ipamd.go:1546","msg":"IP already in DS"}
...
{"level":"info","ts":"2022-04-12T18:13:16.976Z","caller":"ipamd/ipamd.go:1546","msg":"Adding 100.68.63.219/32 to DS for eni-08c872dba81641a42"}
{"level":"info","ts":"2022-04-12T18:13:16.976Z","caller":"ipamd/ipamd.go:1546","msg":"IP already in DS"}
{"level":"info","ts":"2022-04-12T18:13:51.327Z","caller":"aws-k8s-agent/main.go:27","msg":"Starting L-IPAMD   ..."}
```

The IMDS is _still_ not updated, so the new CNI pod has to sync from the EC2 API. However, it retrieves the list of running pods before the IPs from that sync make it into the datastore:

```json
{"level":"info","ts":"2022-04-12T18:13:54.250Z","caller":"awsutils/awsutils.go:1592","msg":"Will attempt to clean up AWS CNI leaked ENIs after waiting 4m41s."}
{"level":"info","ts":"2022-04-12T18:13:54.251Z","caller":"ipamd/ipamd.go:457","msg":"Setting up host network... "}
{"level":"info","ts":"2022-04-12T18:13:54.251Z","caller":"networkutils/network.go:262","msg":"Discovered primary interface: eth0"}
{"level":"info","ts":"2022-04-12T18:13:54.251Z","caller":"ipamd/ipamd.go:457","msg":"Skip updating RPF for primary interface: net/ipv4/conf/eth0/rp_filter"}
{"level":"info","ts":"2022-04-12T18:13:54.251Z","caller":"networkutils/network.go:365","msg":"Discovered primary interface: eth0"}
{"level":"info","ts":"2022-04-12T18:13:54.442Z","caller":"ipamd/ipamd.go:463","msg":"Got network cardindex 0 for ENI eni-08c872dba81641a42"}
{"level":"info","ts":"2022-04-12T18:13:54.442Z","caller":"ipamd/ipamd.go:463","msg":"eni-08c872dba81641a42 is of type: interface"}
{"level":"info","ts":"2022-04-12T18:13:54.442Z","caller":"awsutils/awsutils.go:1201","msg":"logOutOfSyncState: DescribeNetworkInterfaces(eni-08c872dba81641a42) yielded private IPv4 addresses 100.68.33.202,100.68.35.149,100.68.35.40,100.68.36.147,100.68.37.227,100.68.40.230,100.68.41.40,100.68.42.38,100.68.55.166,100.68.58.43,100.68.61.197,100.68.63.104,100.68.63.144,100.68.63.219 that were not yet found in IMDS."}
{"level":"info","ts":"2022-04-12T18:13:54.442Z","caller":"ipamd/ipamd.go:463","msg":"Got network cardindex 0 for ENI eni-0c7c58f6368533bd1"}
{"level":"info","ts":"2022-04-12T18:13:54.442Z","caller":"ipamd/ipamd.go:463","msg":"eni-0c7c58f6368533bd1 is of type: interface"}
{"level":"info","ts":"2022-04-12T18:13:54.442Z","caller":"ipamd/ipamd.go:487","msg":"Found ENIs having 1 secondary IPs and 0 Prefixes"}
{"level":"info","ts":"2022-04-12T18:13:54.442Z","caller":"ipamd/ipamd.go:415","msg":"ENI eni-0c7c58f6368533bd1 set up."}
{"level":"info","ts":"2022-04-12T18:13:54.442Z","caller":"networkutils/network.go:904","msg":"Setting up network for an ENI with IP address 100.68.41.92, MAC address 06:ad:59:59:f9:65, CIDR 100.68.32.0/19 and route table 2"}
{"level":"info","ts":"2022-04-12T18:13:54.443Z","caller":"ipamd/ipamd.go:487","msg":"Found ENIs having 1 secondary IPs and 0 Prefixes"}
{"level":"info","ts":"2022-04-12T18:13:54.443Z","caller":"ipamd/ipamd.go:415","msg":"ENI eni-08c872dba81641a42 set up."}
{"level":"info","ts":"2022-04-12T18:13:54.443Z","caller":"ipamd/ipamd.go:509","msg":"Reading ipam state from CRI"}
{"level":"info","ts":"2022-04-12T18:13:54.446Z","caller":"ipamd/ipamd.go:509","msg":"datastore: Sandbox _migrated-from-cri/c32c2fa0bf126622bc2c3c0f43fda78ff75912cdb78729d3f1fe87bf209758ca/unknown uses unknown IP Address 100.68.61.197 - presuming stale/dead"}
{"level":"info","ts":"2022-04-12T18:13:54.446Z","caller":"ipamd/ipamd.go:509","msg":"datastore: Sandbox _migrated-from-cri/cdcee44ae7b074c002d321a88dbda867a6918084e45e6aa15a68f8ab71048b29/unknown uses unknown IP Address 100.68.42.38 - presuming stale/dead"}
{"level":"info","ts":"2022-04-12T18:13:54.446Z","caller":"ipamd/ipamd.go:509","msg":"datastore: Sandbox _migrated-from-cri/94fe6dd3ea800537f7c86bf12f5ff31643fdf91d2296770ce5cc2e108046bf71/unknown uses unknown IP Address 100.68.58.43 - presuming stale/dead"}
{"level":"info","ts":"2022-04-12T18:13:54.446Z","caller":"ipamd/ipamd.go:509","msg":"datastore: Sandbox _migrated-from-cri/be11ae75f40d6dfc666fb96a568f94ebc264122000af5edb3752389e1d092e1a/unknown uses unknown IP Address 100.68.41.40 - presuming stale/dead"}
{"level":"info","ts":"2022-04-12T18:13:54.446Z","caller":"ipamd/ipamd.go:541","msg":"Get Node Info for: ip-10-7-8-73.eu-west-1.compute.internal"}
{"level":"info","ts":"2022-04-12T18:13:54.647Z","caller":"ipamd/ipamd.go:935","msg":"Trying to allocate 14 IP addresses on ENI eni-08c872dba81641a42"}
{"level":"info","ts":"2022-04-12T18:13:55.100Z","caller":"ipamd/ipamd.go:1077","msg":"Adding 100.68.61.197/32 to DS for eni-08c872dba81641a42"}
{"level":"info","ts":"2022-04-12T18:13:55.100Z","caller":"ipamd/ipamd.go:1077","msg":"Added ENI(eni-08c872dba81641a42)'s IP/Prefix 100.68.61.197/32 to datastore"}
...
{"level":"info","ts":"2022-04-12T18:13:55.100Z","caller":"ipamd/ipamd.go:1077","msg":"Adding 100.68.41.40/32 to DS for eni-08c872dba81641a42"}
{"level":"info","ts":"2022-04-12T18:13:55.100Z","caller":"ipamd/ipamd.go:1077","msg":"Added ENI(eni-08c872dba81641a42)'s IP/Prefix 100.68.41.40/32 to datastore"}
...
```

A couple of seconds later, it concludes that eni-08c... is unused and deletes it:

```json
{"level":"info","ts":"2022-04-12T18:14:57.771Z","caller":"ipamd/ipamd.go:699","msg":"RemoveUnusedENIFromStore eni-08c872dba81641a42: IP/Prefix address pool stats: free 14 addresses, total: 0, assigned: 0, total prefixes: 0"}
{"level":"info","ts":"2022-04-12T18:14:57.771Z","caller":"awsutils/awsutils.go:913","msg":"Trying to free ENI: eni-08c872dba81641a42"}
{"level":"info","ts":"2022-04-12T18:14:58.506Z","caller":"retry/retry.go:70","msg":"Successfully detached ENI: eni-08c872dba81641a42"}
{"level":"info","ts":"2022-04-12T18:15:02.922Z","caller":"retry/retry.go:70","msg":"Successfully deleted ENI: eni-08c872dba81641a42"}
{"level":"info","ts":"2022-04-12T18:15:02.922Z","caller":"awsutils/awsutils.go:913","msg":"Successfully freed ENI: eni-08c872dba81641a42"}
```

Hours later, the pod is noticed in a bad state and manually deleted, and the CNI has no record of the pod:

```json
{"level":"info","ts":"2022-04-12T21:03:00.426Z","caller":"rpc/rpc.pb.go:731","msg":"Received DelNetwork for Sandbox be11ae75f40d6dfc666fb96a568f94ebc264122000af5edb3752389e1d092e1a"}
{"level":"warn","ts":"2022-04-12T21:03:00.426Z","caller":"ipamd/rpc_handler.go:222","msg":"UnassignPodIPAddress: Failed to find sandbox _migrated-from-cri/be11ae75f40d6dfc666fb96a568f94ebc264122000af5edb3752389e1d092e1a/unknown"}
{"level":"info","ts":"2022-04-12T21:03:00.464Z","caller":"rpc/rpc.pb.go:731","msg":"Send DelNetworkReply: IPv4Addr , DeviceNumber: 0, err: datastore: unknown pod"}
```

So it seems like the startup process should wait for the datastore to be populated with the attached IPs before permanently forgetting about running pods.

**Attach logs**
Will send full log bundle by email.

**What you expected to happen**:
The CNI should not delete the ENI currently in-use by pods on the node.

**How to reproduce it (as minimally and precisely as possible)**:
Reproducing this in a natural environment may be a challenge since it relies on the IMDS being stale, but I would bet that it reproduces readily if you run a modified version of the binary that filters out all but the primary interface from `GetMACs`. Just restart it after it allocates a few IPs.

**Anything else we need to know?**:
N/A

**Environment**:
- Kubernetes version (use `kubectl version`): 1.20.10
- CNI Version: 1.10.2
- OS (e.g: `cat /etc/os-release`): Amazon Linux 2
- Kernel (e.g. `uname -a`): 5.4.181-99.354.amzn2.x86_64

### PR DESCRIPTION
**Pull request by jayanthvn**
**What type of PR is this?**
bug

**Which issue does this PR fix**:
Fixes #1834 
Fixes #1872 

**What does this PR do / Why do we need it**:
1. During reconciling or even startup, IPAMD calls tryAssignCidr and adds the IPs/Prefixes to datastore once EC2 allocates the IPs and doesn't wait for IMDS to sync. In scenarios where IMDS is out of sync we will end up tagging those pods as stale during restart. Hence similar to Alloc path, we need to wait until IMDS sync is done.

2. While we wait for the IPs to be present in IMDS, we check if the requested CIDRs are available but this can be more than what the ENI supports and we end up waiting in the retry loop. Instead we need to request for min of {IPs/Prefixes needed, max supported on ENI}

3. Make file grouping.

**If an issue # is not available please add repro steps and logs from IPAMD/CNI showing the issue**:
#1834 #1872

**Testing done on this change**:

```
make help

Usage:
  make <target>

Building
  all              Builds Init, CNI and metrics helper container images.
  build-linux      Build the VPC CNI plugin agent using the host's Go toolchain.
  docker           Build VPC CNI plugin & agent container image.
  docker-init      Build VPC CNI plugin Init container image.
  docker-func-test  Run the built CNI container image to use in functional testing
  multi-arch-cni-build-push  Build multi-arch VPC CNI container image.
  multi-arch-cni-init-build-push  Build VPC CNI plugin Init container image.

Run Unit Tests
  unit-test        Run unit tests
  unit-test-race   Run unit tests with race detection (can only be run natively)

Build and Run Unit Tests
  build-docker-test  Build the unit test driver container image.
  docker-unit-tests  Run unit tests inside of the testing container image.

Build metrics helper agent
  build-metrics    Build metrics helper agent.
  docker-metrics   Build metrics helper agent Docker image.

Run metrics helper Unit Tests
  metrics-unit-test  Run metrics helper unit test suite (must be run natively).
  docker-metrics-test  Run metrics helper unit test suite in a container.
  plugins          Fetch the CNI plugins

Debug script
  debug-script     Fetching debug script from awslabs/amazon-eks-ami

Formatting
  check            Run all source code checks.
  lint             Run golint on source code.
  vet              Run go vet on source code.
  docker-vet       Run go vet inside of a container.
  format           Format all Go source code files. (Note! integration_test.go has an upstream import dependency that doesn't match)

Generate ENI/IP limits
  generate-limits  Generate limit file go code

Cleanup
  clean            Clean temporary files and build artifacts from the project.

Helpers
  help             Display this help
```

Will update rest of UTs

**Automation added to e2e**:

Yes

**Will this PR introduce any new dependencies?**:

No, EC2 calls will reduce since reconciler on adding IPs would make an ec2 call now instead it will wait for IMDS sync.

**Will this break upgrades or downgrades. Has updating a running cluster been tested?**:
No

**Does this change require updates to the CNI daemonset config files to work?**:

No

**Does this PR introduce any user-facing change?**:

No

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by orsenthil — DISMISSED** [review]
LGTM.

**Comment by jayanthvn** [comment]
Thanks Senthil. I am running few UTs, will update it and the merge.

File: pkg/ipamd/ipamd.go [hunk 1]
```diff
@@ -942,13 +942,12 @@ func (c *IPAMContext) tryAssignIPs() (increasedPool bool, err error) {
 				return false, errors.Wrap(err, fmt.Sprintf("failed to allocate one IP addresses on ENI %s, err ", eni.ID))
 			}
 		}
-		// This call to EC2 is needed to verify which IPs got attached to this ENI.
-		ec2Addrs, err := c.awsClient.GetIPv4sFromEC2(eni.ID)
+		eniMetadata, err := c.awsClient.WaitForENIAndIPsAttached(eni.ID, resourcesToAllocate)
```
Comment (M00nF1sh) [inline pkg/ipamd/ipamd.go:945]: resourcesToAllocate seems to be new IPs to allocate.

1. If there are already 8IPs, and we allocate 3 more. this wait will immediately succeed. (and the 3 more additional ip won't be added to pool).
2. what happens if the imds wait timeout, do we have any code that reconciles ip pool on eni at later time?

Comment (jayanthvn) [reply pkg/ipamd/ipamd.go:945]: Reg 1. `ec2Addrs := eniMetadata.IPv4Addresses` should have all the IPs include the new 3 IPs right? Is my understanding correct?

2. yes the reconciler fetches from IMDS and adds those new IPs to datastore.

Comment (jayanthvn) [reply pkg/ipamd/ipamd.go:945]: @M00nF1sh actually it should be (resourcesToAllocate + currentNumberOfAllocatedIPs) for the wait.

**Comment by jayanthvn** [comment]
Ran a simple pod churn test -

1 node, replica 1 to 30 to 0 and repeated 10 runs. Describe interface calls reduced quite significantly -

With 1.11.2 released image ->

Screen Shot 2022-07-20 at 1 36 38 PM

With the fix ->

Screen Shot 2022-07-20 at 1 51 13 PM

API Calls covering both the above timelines ->

Screen Shot 2022-07-20 at 1 52 01 PM

I will be running few more tests to slow down the pod churn and measure the performance. Also will be checking the pod launch time since now we would rely on IMDS sync on increasing IP pool.

**Comment by jayanthvn** [comment]
Adding some delay between pod churns looks good too -

With 1.11.2

Screen Shot 2022-07-20 at 2 46 28 PM


With fix 

Screen Shot 2022-07-20 at 4 12 59 PM

File: pkg/ipamd/ipamd.go [hunk 2]
```diff
@@ -1011,11 +1011,12 @@ func (c *IPAMContext) tryAssignPrefixes() (increasedPool bool, err error) {
 				return false, errors.Wrap(err, fmt.Sprintf("failed to allocate one IPv4 prefix on ENI %s, err: %v", eni.ID, err))
 			}
 		}
-		ec2Prefixes, err := c.awsClient.GetIPv4PrefixesFromEC2(eni.ID)
+		eniMetadata, err := c.awsClient.WaitForENIAndIPsAttached(eni.ID, resourcesToAllocate)
```
Comment (achevuru) [inline pkg/ipamd/ipamd.go]: Above proposed change might end up introducing additional latency in the pod create flow as we now wait for IMDS sync to happen before using the allocated IPs (although the IPs are already attached to the ENIs and are ready to be allocated to pods). Depending on how long the IMDS sync might take - we might run in to noticeable latency increases during pod bring up. Would be good to check with EC2 team on the upper bound for this sync to finish. If it's a big number (30-60s+) then it might not make sense to introduce this dependency in the pod create flow.

Comment (achevuru) [reply pkg/ipamd/ipamd.go]: To add, as discussed offline - I think we should be Ok to do away the additional EC2 call (`GetIPv4PrefixesFromEC2`) and derive the IPs from the o/p of the above Alloc call.

Comment (jayanthvn) [reply pkg/ipamd/ipamd.go]: Yeah I did run few perf tests and saw few seconds delay in the launch time, typically we don't recommend setting warm ip/min ip with pod churn scenarios. But yes to reduce the describe call we can just remove the additional get call rather rely on the return from assign call. However to fix 1967, we might have to handle it in describeALL call so that pods are not marked as stale, which would lead to additional call in reconciler if IMDS never gets synced. We already have a metrics to capture IMDS sync errors.

Comment (jayanthvn) [reply pkg/ipamd/ipamd.go]: I am checking with IMDS team on the SLA.

**Comment by jayanthvn** [comment]
This will introduce a bit of delay in the pod launch time during churn scenarios since we rely on IPs to be available in IMDS. So I will be splitting the PR, one with make file changes and reducing the describe call and another with just the dependency on IMDS for #1967 which might need more analysis.

**Review by M00nF1sh — APPROVED** [review]
