### PR TITLE
Calico integration Tests

### LINKED ISSUE #1874: Fix calico tests in the weekly test suite
**What would you like to be added**:
Currently, calico tests in [weekly test suite](https://github.com/aws/amazon-vpc-cni-k8s/runs/5234976037?check_suite_focus=true) is failing with error of 
`/home/github-runner/go/src/github.com/aws/amazon-vpc-cni-k8s/amazon-vpc-cni-k8s/scripts/../config/master/calico.yaml DOES NOT exist.
`
This calico test would need to be modified to install Calico using Helm charts as recommended [here](https://docs.aws.amazon.com/eks/latest/userguide/calico.html) and the test would need to  verify  network policy application as mentioned [here](https://docs.aws.amazon.com/eks/latest/userguide/calico.html#calico-stars-demo)

**Why is this needed**:
To fix the Calico test suite in the weekly test suite run.

### PR DESCRIPTION
**Pull request by haouc**
**What type of PR is this?**
This PR is fixing a failing weekly Calico integration tests and replacing it with helm installation with demoed STAR network policy tests suite. 

bug
**Which issue does this PR fix**:
Fixes #1874 

**What does this PR do / Why do we need it**:
We have deprecated support of Calico charts in this repo, but we need do routine integration tests with certain/latest calico version with our VPC CNI. This PR contains the following changes/additions:

1. Helm installation of Calico operator with a given version of Calico
2. STAR tests with various network policy settings
3. Calico tests are no longer using bash scripts. Ginkgo suite is used to implement the tests
4. New ENVs to config tests: RUN_LATEST_CALICO_VERSION (boolean) that indicates if fetching Calico repo to use the latest Calico released version; CALICO_VERSION (boolean) that sets Calico version to test if the `RUN_LATEST_CALICO_VERSION == false`
5. If `DEPROVISION == false`, EC2 instances will be terminated to avoid impact for future tests in the cluster
6. Reorganized VPC CNI tests on current image with Calico tests to avoid interference 
7. Due to installing AMD arch based Calico images and STAR resources, during the tests ARM arch nodes will be unschedulable. They will be restored to schedulable state after Calico tests are finished
9. To utilize the recently added metrics infra, Calico tests also add a new metrics `calico_test_status`
10. If the ENV `RUN_CALICO_TEST_WITH_PD` NOT set, the script will also run PD with Calico by default

**If an issue # is not available please add repro steps and logs from IPAMD/CNI showing the issue**:

**Testing done on this change**:

Using specified Calico version:
```
$ RUN_CALICO_TEST=true CALICO_VERSION=3.21.0 ./scripts/run-integration-tests.sh
...
2022-03-04 07:49:42 [✔]  EKS cluster "cni-test-16533" in "us-west-2" region is ready
ok.
TIMELINE: Upping test cluster took 1079 seconds.
...
=== RUN   TestIntegration
Mar  4 07:49:44.618: INFO: The --provider flag is not set. Continuing as if --provider=skeleton had been used.
Running Suite: Amazon VPC CNI Integration Tests
...
Ran 2 of 2 Specs in 31.384 seconds
SUCCESS! -- 2 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestIntegration (31.38s)
...
TIMELINE: Current image integration tests took 21 seconds.
Starting Helm installing Tigera operator and running Calico STAR tests
~/environment/go/src/amazon-vpc-cni-k8s/test ~/environment/go/src/amazon-vpc-cni-k8s
Using Calico version 3.21.0 to test   <-----
Running Suite: Calico with VPC CNI e2e Test Suite
=================================================
Random Seed: 1646380248
Will run 22 of 22 specs
...
STEP: Restore ARM64 Nodes Schedulability
 
Ran 22 of 22 Specs in 379.131 seconds
SUCCESS! -- 22 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS
 
Ginkgo ran 1 suite in 6m24.072209201s
Test Suite Passed
~/environment/go/src/amazon-vpc-cni-k8s
Deleting cluster  (this may take ~10 mins) ... ok.
TIMELINE: Down processes took 420 seconds.
```

Using latest Calico released version (Automatically fetching from Calico)
```
% RUN_CALICO_TEST=true RUN_LATEST_CALICO_VERSION=true ./scripts/run-integration-tests.sh
...
TIMELINE: Current image integration tests took 39 seconds.
Starting Helm installing Tigera operator and running Calico STAR tests
~/go/src/amazon-vpc-cni-k8s/test ~/go/src/amazon-vpc-cni-k8s
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 19996    0 19996    0     0  43094      0 --:--:-- --:--:-- --:--:-- 43094
Using Calico version v3.22.1 to test   <-----
Running Suite: Calico with VPC CNI e2e Test Suite
=================================================
Random Seed: 1646377066
Will run 22 of 22 specs

...
STEP: Restore ARM64 Nodes Schedulability
 
Ran 22 of 22 Specs in 373.879 seconds
SUCCESS! -- 22 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS
 
Ginkgo ran 1 suite in 6m24.177285169s
Test Suite Passed
~/go/src/amazon-vpc-cni-k8s
Deleting cluster  (this may take ~10 mins) ... ok.
TIMELINE: Down processes took 442 seconds.
```
Prefix Delegation tests
```
STEP: Restore ARM64 Nodes Schedulability

Ran 22 of 22 Specs in 378.191 seconds
SUCCESS! -- 22 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS

Ginkgo ran 1 suite in 6m24.845380702s
Test Suite Passed
~/go/src/amazon-vpc-cni-k8s
Run Calico tests with Prefix Delegation enabled
daemonset.apps/aws-node env updated
{
    "TerminatingInstances": [
        {
            "CurrentState": {
                "Code": 32,
                "Name": "shutting-down"
            },
            "InstanceId": "i-0341454b54c510205",
            "PreviousState": {
                "Code": 16,
                "Name": "running"
            }
        }
    ]
}
Waiting 15 minutes for new nodes being ready

Starting Helm installing Tigera operator and running Calico STAR tests
~/go/src/amazon-vpc-cni-k8s/test ~/go/src/amazon-vpc-cni-k8s
Using Calico version 3.22.0 to test
Running Suite: Calico with VPC CNI e2e Test Suite
=================================================
Random Seed: 1646727202
Will run 22 of 22 specs
...
STEP: Restore ARM64 Nodes Schedulability

Ran 22 of 22 Specs in 370.725 seconds
SUCCESS! -- 22 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS

Ginkgo ran 1 suite in 6m18.087117999s
Test Suite Passed

```

**Automation added to e2e**:

yes
**Will this PR introduce any new dependencies?**:

no
**Will this break upgrades or downgrades. Has updating a running cluster been tested?**:
no

**Does this change require updates to the CNI daemonset config files to work?**:

no
**Does this PR introduce any user-facing change?**:

no
```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: scripts/run-integration-tests.sh [hunk 1]
```diff
@@ -270,6 +248,35 @@ if [[ $TEST_PASS -eq 0 ]]; then
...
+      calico_version=$(echo $version_tag | cut -d ":" -f 2 | cut -d '"' -f 2 )
+    else
+      echo "Getting Calico latest version failed, will fall back to default/set version $calico_version instead"
+    fi
+  fi
+  echo "Using Calico version $calico_version to test"
+  ginkgo -v e2e/calico -- --cluster-kubeconfig=$KUBECONFIG --cluster-name=$CLUSTER_NAME --aws-region=$AWS_DEFAULT_REGION --aws-vpc-id=$VPC_ID --calico-version=$calico_version
+  popd
+  
+  if [[ "$DEPROVISION" == false ]]; then
```
Comment (vikasmb) [inline scripts/run-integration-tests.sh:269]: I think DEPROVISION is set to false only when we want to login to the cluster nodes and debug. As such, automated termination of nodes may not be needed here. Thoughts ?

File: test/framework/controller/installation_manager.go [hunk 2]
```diff
@@ -24,6 +24,9 @@ import (
 type InstallationManager interface {
 	InstallCNIMetricsHelper(image string, tag string) error
 	UnInstallCNIMetricsHelper() error
+	InstallTigeraOperator(version string) error
+	UninstallTigeraOperator() error
+	//AddAndUpdateRepository(entry repo.Entry)
```
Comment (vikasmb) [inline test/framework/controller/installation_manager.go:29]: Can we remove this commented code ?

File: scripts/run-integration-tests.sh (hunk 1 above)
Comment (haouc) [reply scripts/run-integration-tests.sh:269]: Are we planning to recycle the cluster? @jayanthvn

File: test/framework/controller/installation_manager.go (hunk 2 above)
Comment (haouc) [reply test/framework/controller/installation_manager.go:29]: Thanks for catching this. Will remove it.

File: scripts/run-integration-tests.sh (hunk 1 above)
Comment (haouc) [reply scripts/run-integration-tests.sh:269]: I feel we should keep this in case the Calico tests interfere with any tests without awareness in the future.

File: test/e2e/calico/calico_suite_test.go [hunk 3]
```diff
@@ -0,0 +1,269 @@
...
+var _ = BeforeSuite(func() {
+	f = framework.New(framework.GlobalOptions)
+	By("installing Calico operator")
+
+	tigeraVersion := f.Options.CalicoVersion
+	err := f.InstallationManager.InstallTigeraOperator(tigeraVersion)
+	Expect(err).ToNot(HaveOccurred())
+
+	By("Patching ARM64 node unschedulable")
+	err = updateNodesSchedulability("beta.kubernetes.io/arch", "arm64", true)
```
Comment (jayanthvn) [inline test/e2e/calico/calico_suite_test.go:45]: Can we instead use "kubernetes.io/arch" ? I know we do tag with beta still but better to use "kubernetes.io/arch".

File: test/e2e/calico/calico_suite_test.go [hunk 4]
```diff
@@ -0,0 +1,269 @@
...
+
+var _ = BeforeSuite(func() {
+	f = framework.New(framework.GlobalOptions)
+	By("installing Calico operator")
+
+	tigeraVersion := f.Options.CalicoVersion
+	err := f.InstallationManager.InstallTigeraOperator(tigeraVersion)
+	Expect(err).ToNot(HaveOccurred())
+
+	By("Patching ARM64 node unschedulable")
```
Comment (jayanthvn) [inline test/e2e/calico/calico_suite_test.go:44]: Is there a reason we mark it unschedulable?

File: test/e2e/calico/calico_suite_test.go [hunk 5]
```diff
@@ -0,0 +1,269 @@
...
+		ImagePullPolicy(v1.PullAlways).
+		Port(v1.ContainerPort{ContainerPort: 9001}).
+		Build()
+	uiDeployment := manifest.NewCalicoStarDeploymentBuilder().
+		Namespace(uiNamespace).
+		Name("management-ui").
+		Container(uiContainer).
+		Replicas(1).
+		PodLabel("role", "management-ui").
+		NodeSelector("beta.kubernetes.io/arch", "amd64").
```
Comment (jayanthvn) [inline test/e2e/calico/calico_suite_test.go:68]: Same as above.

File: test/e2e/calico/calico_suite_test.go (hunk 4 above)
Comment (jayanthvn) [reply test/e2e/calico/calico_suite_test.go:44]: Oh is it because star policy is still not supported for ARM instance types?

**Comment by jayanthvn** [comment]
Can we also add these tests with PD enabled? We can run the test with secondary IP mode, enable PD, ASG can be reduced to 0 and again back to few nodes and then run the test again.

File: test/e2e/calico/calico_suite_test.go (hunk 4 above)
Comment (haouc) [reply test/e2e/calico/calico_suite_test.go:44]: Cordon these arm nodes to avoid Calico tests pods deployed to them. For now the provided tests containers are for AMD.

File: test/e2e/calico/calico_suite_test.go (hunk 3 above)
Comment (haouc) [reply test/e2e/calico/calico_suite_test.go:45]: make sense. I will change this to not use `beta`.

**Comment by haouc** [comment]
> Can we also add these tests with PD enabled? We can run the test with secondary IP mode, enable PD, ASG can be reduced to 0 and again back to few nodes and then run the test again.

PD tests were added.

**Review by jayanthvn — APPROVED** [review]
lgtm

**Review by vikasmb — APPROVED** [review]
lgtm
