### PR TITLE
Use symmetric return path for non-VPC traffic - alternate solution

### LINKED ISSUE #1392: Traffic from outside VPC does not reach pod
**What happened**:

For some reason, UDP traffic from outside the VPC is not reaching the pod. Traffic flow logs show UDP traffic flowing through the load balancer and being sent to the correct internal address. UDP traffic has been confirmed (via `tcpdump`) to reach the primary IP of the ENI that hosts the pod's IP, but does not reach the pod. UDP traffic from inside the VPC does reach the pod as expected. TCP traffic from both inside and outside the VPC reaches the pod as expected.

AWS Support has confirmed that security groups are properly configured to allow access. 

**Attach logs**

Logs are attached to AWS Support case 7990499551 which I opened 16 days ago but remains unresolved. I feel like the ticket is not getting directed to the right team, which is why I am opening this issue. I think this is a CNI bug.

**What you expected to happen**:

With a pod listening on a UDP port and a security group allowing access from `0.0.0.0/0`, I expect traffic targeted to that UDP port to be delivered, regardless of its source address, 

**How to reproduce it (as minimally and precisely as possible)**:

1. Create an EKS cluster with a node pool in a private subnet using default configuration.
1. Create a target Pod server on a secondary ENI on one of the nodes. The only way I know to do this is to first create enough pods to fill up the first ENI. 
2. Create a load balancer target group targeting the target pod on its pod IP address (not the ENI or Node IP address).  **Critical**: ensure "Preserve Client IP" is enabled.
3. Provision a Network load balancer to forward traffic to the target Pod. 

At this point, the configuration is complete and you should be able to communicate from the public internet to the Pod using the NLB's DNS name. However, the connection does not work. On the other hand, you can verify that the Pod is serving traffic properly by connecting to it from any host in the private subnet on the same IP as is specified in the target group.

<details><summary>~~Original version~~</summary>

I don't know. The entire configuration, from creating the VPC through creating the EKS cluster through deploying the Pod, Kubernetes service, and load balancer, was all provisioned with Terraform and Helm. The almost exactly the same configuration was applied in another account and works fine as expected. (The differences between the 2 configurations are things like ID names, DNS names, ARNs, etc. that have to be different between different installations, but basically the configurations are identical in what should be all relevant aspects.) 

As deployed, the only noticeable difference is that the working instance has the Pod deployed on the EC2 instance's primary ENI and the non-working instance has the pod deployed on a secondary ENI.
</details>

**Anything else we need to know?**:

The default configuration leaves `aws-node` with `AWS_VPC_K8S_CNI_EXTERNALSNAT: false`. You can check with 
```
$  kubectl -n kube-system describe daemonset aws-node | grep EXTERNALSNAT
      AWS_VPC_K8S_CNI_EXTERNALSNAT:        false
```

Unfortunately, this is incompatible with allowing Pods to be reached on their private IPs when the source IP is outside the VPC. This issue can be fixed by setting `AWS_VPC_K8S_CNI_EXTERNALSNAT=true` but there is no AWS API for doing that, thus it is not practical to set in a large organization. 

1. The CNI should be smart enough to bypass SNAT when the connection is initiated from outside the node on the pod's private IP. 
1. There should be an API and all the corresponding ways (AWS console, `aws` CLI, Terraform, etc.) for setting `AWS_VPC_K8S_CNI_EXTERNALSNAT=true`

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18.9-eks-d1db3c
- CNI Version: amazon-k8s-cni:v1.7.5-eksbuild.1
- OS (e.g: `cat /etc/os-release`): Amazon Linux 2
- Kernel (e.g. `uname -a`): `4.14.209-160.339.amzn2.x86_64 #1 SMP Wed Dec 16 22:44:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

### PR DESCRIPTION
**Pull request by kishorj**
**What type of PR is this?**
bug

**Which issue does this PR fix**:
Fixes #1392, #1423

**What does this PR do / Why do we need it**:
When external SNAT is disabled, this PR does the following
- setup iptables rules to mark egress traffic from pods that are destined to external network
- external traffic will be sent through the primary interface

This is an alternate fix. It doesn't require permissive rp filter configuration on the secondary ENIs, or a new connmark. 

**If an issue # is not available please add repro steps and logs from IPAMD/CNI showing the issue**:
N/A

**Testing done on this change**:

- When external SNAT is enabled, the iptables conmark rules added to the nat table get cleaned up
- With External SNAT disabled
   - connmark rules get added to the nat table
   - pods are able to initiate connections to hosts outside the VPC, traffic is through the primary interface
   - in case of NLB-IP, verify traffic flows as expected for client IP preservation enabled/disabled, pods on primary/secondary interfaces
   - UDP traffic works fine
   - instance mode NLB works as expected - verified externalTrafficPolicy Cluster, Local, IP preservation enabled/disabled, pods on primary/secondary interfaces
   - in-cluster traffic works as expected
   - enabled security group per pod, verified pods can communicate within the cluster, pods can receive client IP preserved traffic from the NLB

- With External SNAT enabled
    - connmark and SNAT rules get removed from the nat table
    - instance mode NLB works fine with IP preserve enabled/disabled, pods on primary/secondary interfaces
    - IP mode NLB works as expected with IP preserve enabled/disabled, pods on primary/secondary interfaces
    - pod can communicate to hosts within or outside VPC
    - enabled security group per pod, verified traffic flows

- New integration tests pass after some modification 

**Automation added to e2e**:

**Will this break upgrades or downgrades. Has updating a running cluster been tested?**:
No impact on upgrade/downgrade. On, downgrade conn mark rules in the nat table remain until node is rebooted, but there is no impact on the functionality.

**Does this change require updates to the CNI daemonset config files to work?**:

**Does this PR introduce any user-facing change?**:

```release-note
Fixes the issue with non-VPC traffic ingress from secondary ENIs when external SNAT feature is not used.
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: pkg/networkutils/network_test.go [hunk 1]
```diff
@@ -224,25 +224,15 @@ func TestUpdateRuleListBySrc(t *testing.T) {
 			[]string{"10.10.0.0/16", "10.11.0.0/16"},
 			[]string{"10.12.0.0/16", "10.13.0.0/16"},
 			[]netlink.Rule{origRule},
-			make([]netlink.Rule, 4),
-			make([]*net.IPNet, 4),
-			[]int{origRule.Table, origRule.Table, origRule.Table, origRule.Table},
+			make([]netlink.Rule, 1),
```
Comment (anguslees) [inline pkg/networkutils/network_test.go:227]: Nit: Some of these test parameters look like they're not useful anymore - and we can probably simplify these structures and the below code.

**Review by anguslees — APPROVED** [review]

File: pkg/networkutils/network_test.go (hunk 1 above)
Comment (kishorj) [reply pkg/networkutils/network_test.go:227]: ack. I will do it in a follow up commit.

**Review by jayanthvn — APPROVED** [review]

File: pkg/networkutils/network.go [hunk 2]
```diff
@@ -451,10 +452,98 @@ func (n *linuxNetwork) SetupHostNetwork(vpcCIDRs []string, primaryMAC string, pr
...
+
+	var iptableRules []iptablesRule
+	log.Debugf("Setup Host Network: iptables -t nat -A PREROUTING -i eni+ -m comment --comment \"AWS, outbound connections\" -m state --state NEW -j AWS-CONNMARK-CHAIN-0")
+	iptableRules = append(iptableRules, iptablesRule{
+		name:        "connmark rule for non-VPC outbound traffic",
+		shouldExist: !n.useExternalSNAT,
+		table:       "nat",
+		chain:       "PREROUTING",
+		rule: []string{
+			"-i", "eni+", "-m", "comment", "--comment", "AWS, outbound connections",
```
Comment (kishorj) [inline pkg/networkutils/network.go:485]: If AWS_VPC_K8S_CNI_VETHPREFIX is configured to something else than eni, this doesn't work. Need to make it based on the veth prefix configuration.

Comment (kishorj) [reply pkg/networkutils/network.go]: fixed in new commit.

File: README.md [hunk 3]
```diff
@@ -376,7 +376,7 @@ Type: String
 
 Default: `eni`
 
-Specifies the veth prefix used to generate the host-side veth device name for the CNI. The prefix can be at most 4 characters long.
+Specifies the veth prefix used to generate the host-side veth device name for the CNI. The prefix can be at most 4 characters long. The prefixes `eth` or `vlan` or `lo` are reserved and cannot be specified. We recommend using exclusive prefix for the host side veth device names.
```
Comment (achevuru) [inline README.md:379]: Are they really reserved though? We do create an eth0/1 in container ns. If the idea is to encourage users to avoid specifying some common linux interface prefixes, maybe we can have a generic statement here suggesting to avoid them(?). Because we probably can include more prefixes beyond the ones specified here (tun, tap, br etc)....

File: scripts/entrypoint.sh [hunk 4]
```diff
@@ -42,6 +42,18 @@ validate_env_var()
...
         exit 1     
     fi 
+
+    if [[ ${#AWS_VPC_K8S_CNI_VETHPREFIX} -gt 4 ]]; then
+        log_in_json error "AWS_VPC_K8S_CNI_VETHPREFIX cannot be longer than 4 characters"
+        exit 1
+    fi
+
+    case ${AWS_VPC_K8S_CNI_VETHPREFIX} in
+        eth|vlan|lo)
```
Comment (achevuru) [inline scripts/entrypoint.sh:52]: Same comment as above

File: README.md (hunk 3 above)
Comment (kishorj) [reply README.md:379]: These are not reserved by linux, these are reserved only by the CNI plugin.

Comment (achevuru) [reply README.md:379]: Might help to call that out specifically. Also, we basically don’t want any other interfaces on the instance to share the same prefix as host veth interfaces and I think we should specify that in the above description so that customers know the prefixes to avoid in addition to the above three we are validating.

Comment (kishorj) [reply README.md]: updated readme.

File: scripts/entrypoint.sh (hunk 4 above)
Comment (kishorj) [reply scripts/entrypoint.sh:52]: updated readme

**Review by achevuru — APPROVED** [review]

**Comment by jayanthvn** [comment]
Lets wait for the integration tests to finish.
